travis:
  secure:
    BINSTAR_TOKEN: bUu/AKoMU+QZI+2h7ngx0zGYYWJPw0jXiHX3pRPargGEsyg8uGnFX0IrDUMgXwLpQvhOF7aT+VQeJXjQ7/OQEAVxCMMkHCk7sFVWZJAU739Y2HJsg89ER8LKhAlqQ+rUwq8OeYhRRw+NPg9uQwHibCNLLONWyTfy6zUB0J27QD1nmMszLCJ0bPoiXacoOJeuao9jh0LT0Q/l3JM9GfFd7/OYoVIyIXGLTcdmWT1tOcH5FT7QDEm/SzLoAMFu4KBQ92YfC7rlOjQzxhF9kgCP1t2m1rbPhpNBdRETKhv5/5kgeQXoqSW6h7ZQM80AOvQNBSRB1H62zuVU4Vhs/BpQZs4WiJtxH38ZDgdnf9zJZMlIOtDDMb9dOyLsqHDO37OiKySdek1CYRJ40vU7t6D/Z8XB+uPYHbh6oYgPGfd19zNF2nfLRUSxaSmCoMvWk4pkJ+roDz4cVAXcVvF8U4FVId45HHpGgOGE0wzF4t16xXxZOo6N+IJgUpxkmQfBK3TbGX7yF0prH/dzgxggkDdbCOiRW0KpxRbsyfrvP3k4lHDpR13f17GJXCuaThc/+IywHcpR8UrEN5aVKKpaG8T12JRTVt/olNI/B8A+LuQVewDVAYDoS9I7P95qHQIDLyw1jDNLpRrMw3N/6On6OIlGXb3hX6dKQ0h7gMJoqlGZ/AE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
